### ISSUE TITLE
Program getting stuck on function calls

### ISSUE THREAD

**Issue by LYuriy** [pololu/l3g-arduino#10]
Hi, I'm trying to run the Serial example in the library, but I'm having issues. I've imported the library, I'm using an Arduino Uno, and the program compiles without issues. But when I run it, it stops when it encounters a function from the library. So, for example, it'll output basic Serial.println text outputs before any function from the library, and after a l3g function it doesn't output anything. Neither while(gyro.init()) nor while(!gyro.init()) loop will work for checking the detection, there's no text output inside the loop, it seems to just get stuck on the gyro.init. I've tried using the adafruit l3g20h code, and it works fine. I also noticed that if I manually enter (L3G::device_D20, L3G::sa0_high) into the function parameters then it gets past that function call, but since there are functions without any parameters, that can't always work. Does anyone know what the issue could be?
Thanks

**Comment by kevin-pololu** [comment]
Hello,
This kind of problem usually means there is some kind of wiring problem or a problem with the board itself, though I am not sure why the Adafruit code would work with your gyro while our library doesn't. I don't think it's a library issue, though, so please contact us through our regular support channels to continue troubleshooting with us: https://www.pololu.com/contact

When you contact us, it would be helpful if you could tell us which board you have and provide a picture showing how you have it connected. Please also confirm whether the Adafruit code is fully working for you (i.e. you're successfully getting data out of the sensor with it).
