### ISSUE TITLE
How to change the FS range of the sensor?

### ISSUE THREAD

**Issue by sarimzafar** [pololu/l3g-arduino#13]
So the function enableDefault() sets the FS range to 250 dps. How can I manually change the default range to say 2000 dps?

So I navigated to the function enableDefault() inside the library and found out that we write a certain value to the CTRL4 register. Does anyone know what value can be changed there to make it switch to 2000 dps?

**Comment by kevin-pololu** [comment]
Hi, sarimzafar.

The fields inside the configuration registers and their meanings can be found in the datasheets for the sensors, which can be found on their carrier boards' product pages on the Pololu website. In general, we recommend carefully reading the datasheet for your sensor to understand how to work with it.

If you have additional questions, please post on the [Pololu forum](https://forum.pololu.com/) or [contact us directly](https://www.pololu.com/contact); GitHub issues are intended for tracking problems and improvements in the library code.

Kevin
