### ISSUE TITLE
can someone please help me with some error correction?

### ISSUE THREAD

**Issue by boredcoder411** [pololu/l3g-arduino#15]
![Screenshot (80)](https://user-images.githubusercontent.com/105937655/190917719-54a31461-8c1d-4dfb-9032-09e45e2ed5fd.png)
as you can see on the serial monitor, the readings vary a lot even when the gyro is stationary... thus i am looking for some type of error correction. any help is appreciated. thank you

**Comment by kevin-pololu** [comment]
Hi,

Please post your question on the [Pololu forum](https://forum.pololu.com/), which is a more appropriate place for troubleshooting. It would be helpful if you could post some of the raw sensor output from the unmodified Serial example too. The GitHub Issues are intended for discussion about problems and improvements in the library code.

Kevin
