### ISSUE TITLE
Configuration to work on Due's additional I2C port

### ISSUE THREAD

**Issue by zacsketches** [pololu/l3g-arduino#9]
Pololu, I appreciate your outstanding libraries for the l3g and the lsm303.

I'm using them both on the Arduino Due to build a drift compensated gyro with an experimental Newton-Cotes based numerical integration on the gyro.

The complication I ran into is that the Due has two I2C ports.  The default is on pins 20/21 and are activated when you call Wire.begin().  However, more convenient for my build are the SCL1/SDA1 pins closer to the AREF pin that are activated when you call Wire1.begin().

You library uses direct calls to Wire throughout (i.e. `Wire.write()`, `Wire.beginTransmission()`, etc).  So I rewrote the library to configure which I2C port users want their L3G or LSM303 objects to communicate through.  To keep things simple for new Arduino users I set the default to the normal Wire library so all of your existing examples still work.  The new constructor definition looks like this.

`LSM303(I2C_port::port p = I2C_port::primary);`

If you are interested in seeing this functionality, I can open a pull request and you can check it out.

**Comment by kevin-pololu** [comment]
Thanks for sharing your solution. For now, I don't think we want to include this change in the Pololu repository, but we can definitely keep it in mind as a resource for others who want to use the Due's second I2C port.
